---
- hosts: node
  become: true
  tasks:
    - name: install docker
      yum:
        pkg: docker
        state: present
    - name: install git
      yum:
        pkg: git
        state: present
    - name: start docker
      service:
        name: docker
        state: started
    - name: pull the docker file
      command: docker pull devopsedu/webapp:latest
    - name: run the docker file
      command: docker run -it -P --name webappimage devopsedu/webapp

